# -*- coding: utf-8 -*-
"""Calculater

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16vdfBiNKLotcrcjY2xmFYpIzYVgxSTq7
"""

def check_selection(selection):
  match selection:
    case 1:
      answer = num1 + num2
      print("\n", num1, "+", num2, "=", answer)
    case 2:
      answer = num1 - num2
      print("\n", num1, "-", num2, "=", answer)
    case 3:
      answer = num1 / num2
      print("\n", num1, "/", num2, "=", answer)
    case 4:
      answer = num1 * num2
      print("\n", num1, "*", num2, "=", answer)
  if selection > 4 or selection < 1:
      print("\nInvalid Input")


running = 1

while running == 1:
  while True:
    try:
      num1 = int(input("\nFirst Number: "))
      break
    except ValueError as ve:
      print("\nInvalid Input")

  while True:
    try:
      num2 = int(input("Second Number: "))
      break
    except ValueError as ve:
      print("\nInvalid Input")

  print("\n1. Addition\n2. Subtraction\n3. Division\n4. Multiplication")
  selection = int(input("Your Selection: "))
  check_selection(selection)

  print("\nRestart? Type: Yes")
  restart = str(input("Your Selection: "))
  if restart == "YES" or "yes" or "Yes" or "yES" or "yEs" or "YeS" or "YEs":
    pass
  else:
    running = 0